aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "amilajack@users.noreply.github.com"
            git config --global user.name "Amila Welihinda"
            echo "machine github.com login amilajack password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=amilajack yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
        filters: *filter-only-master