name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and npm
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: npm test
        run: npm test
